### ISSUE TITLE
If repository is already cloned from previous run do pull before commit.

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#1]
Replicate:
1) update image with script
2) do any commit to same repo from another source
3) try to update image again

It should always do a pull to update the local repository before commit and push.
In case push fails, it should try to pull and merge(if there are no conflicts) - then push again.

```
git commit was successful
using SSH key defined in /go/gitops/id_rsa
[error] non-fast-forward update: refs/heads/develop
```

In case there is conflict in pull+merge then it should fail(exit non 0)

**Comment by kertkukk** [comment]
[Go-git](https://github.com/go-git/go-git) Library that is used to to Git operations does not support merge. So if commit has conflicts then instead of pull and merge, git clone and pull is going to be made. Implementation in [94f3101a](https://github.com/entigolabs/entigo-k8s-gitops/commit/94f3101ac82ac232c81c1ae851ce5270075cfd4b).

**Comment by martivo** [comment]
Works. The commit gets done even if some change happened between clone and push.
